version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - brenetic
  - njseeto
  - mattempty
