sequenceDiagram
%% width:1200
%% height:2400

participant U as User
participant R as Runner
participant STC as Service Token Cache
participant SW as Submitter Worker
participant DS as User Data Store API
participant FS as User File Store API
participant VS as Virus Scanner
participant FC as File Checks
participant S3 as User File Store (S3)


Note over SW: Submitter Worker<br>picks up submission

SW->>+FS:request files[s]

FS->>+STC: get service token
STC-->>-FS: return service token

Note over FS: check JWT
Note over FS: check presence of <br>user token/id digest
Note over FS: create s3 key

FS->>+S3:get files[s]
S3-->>-FS:return file[s]

Note over FS: decrypt file[s]

FS-->>-SW:return file[s]

Note over SW: Attach files to<br> output payload
