sequenceDiagram

participant U as User

participant R as Runner

participant DS as User Datastore API

participant DB as User Datastore DB

Note over U: Invoke

U->>+R: POST current page

Note right of U: {<br>  page data<br>  save_return: true<br>}

Note over R: Update userData<br>with page data

R-->>-U: Redirect to /return/setup

Note over U: Process explanation

U->>+R: POST /return/setup

R-->>-U: redirect /return/setup/email

Note over U: Enter email and <br>passphrase (only if <br>2fa mandatory)

U->>+R: POST /return/setup/email

Note right of U: {<br>email,<br>[passphrase]<br>}

Note over R: Add email <br>(and passphrase) <br>to userData

R-->>-U: redirect /return/setup/email/confirm

Note over U: Double-check email

U->>+R: POST /return/setup/email/confirm

Note right of U: {<br>email_confirmed<br>}

Note over R: Get email <br>(and passphrase) <br>from userData
Note over R: Encrypt<br>AES256 with<br>SERVICE_SECRET<br>- email<br>- userId<br>- userToken<br><br>--> encrypted_details

Note over R: Encrypt <br>- email<br>- [passphrase]

R->>+DS: POST /service/:service/savereturn/email/add

Note right of R: {<br>email,<br>encrypted_email<br>[encrypted_passphrase],<br>encrypted_details,<br>duration<br>link_template<br>service_vars: {...}<br>}

DS->>+DB: Find valid record matching encrypted_email

DB-->>-DS: 

alt: if existing email_token record

  DS->>+DB: Update record as invalid

  Note right of DS: {<br>...<br>invalid: superseded<br>}

  DB-->>-DS: 

end

Note over DS: Create email_token<br>UUID v4

Note over DS: Create expiry_time<br>based on duration

DS->>+DB: Create email_token record 

Note right of DS: { <br>type: email_token<br>email_token<br>expiry_time,<br>encrypted_email<br>[encrypted_passphrase]<br>encrypted_details<br> }

DB-->>-DS: 

DS-XU: Send confirmation email via GOV Notify

DS-->>-R:  

R-->>-U: Redirect to /return/setup/email/validate

Note over U: Resend email

alt: Did not get email

  U->>+R: POST /return/setup/email/resend

  R-->>-U: Redirect to /return/setup/email/validate

end

Note over U: --> Confirmation