sequenceDiagram

participant U as User

participant R as Runner

participant DS as User Datastore API

participant DB as User Datastore DB

Note over U: Enter code

U->>+R: POST /return/setup/mobile/code/:mobile_validation_code

Note right of U: {<br>code<br>}

Note over R: Retrieve email<br>from userData

Note over R: Encrypt email

R-->>+DS: POST /service/:service/savereturn/mobile/confirm

Note right of R: {<br>code,<br>encrypted_email<br>}

DS->>+DB: Find matching record

Note right of DS: ? <br>{<br>type: code<br>encrypted_email<br>}

DB-->>-DS:  

Note over DS: check code valid

alt: if code invalid

  DS-->>R:  

  alt: Code used

    R-->>U: error

  else: Code expired

    R-->>U: error

  else: Code invalid

    R-->>U: error

  end

end

  Note over DS: Mark code as used

  DS->>+DB: Update code record 

  Note right of DS: {<br>...<br>invalid: used<br>}

  DB-->>-DS: 

DS-->>-R:   {encrypted_details}

Note over R: Decrypt <br>encrypted_details

Note over R: Add <br>encrypted_details<br>to userData

R-->>-U: Redirect to /return/setup/success

Note over U: --> Create record
