sequenceDiagram

participant U as User

participant R as Runner

participant DS as User Datastore API

participant DB as User Datastore DB

U->>+R: POST /savereturn/create`

Note over R: Get<br>- email,<br>[- mobile]<br>from userData<br>(encrypted_details)

Note over R: Set encrypted_details to<br>{<br>userId,<br>userToken<br>email<br>mobile<br>}

Note over R: Encrypt <br>AES256 with <br>SERVICE_SECRET <br>- email, <br>- encrypted_details

R-->>+DS: POST /service/:service/savereturn/create

Note right of R: {<br>email (options)<br>encrypted_email, <br>encrypted_details<br>}

DS->>+DB: Create record (encrypted_email must be unique)

Note right of DS: {<br>type: savereturn<br>service<br>...<br>}

DB-->>-DS: 

DS-XU: Send record created email via GOV Notify

DS-->>-R: 

R-->>-U:  

Note over U: Ends
