sequenceDiagram

participant U as User

participant R as Runner

participant DS as User Datastore API

participant DB as User Datastore DB

R->>+DS: POST /service/:service/savereturn/signin/code

Note right of R: { <br>mobile<br>encrypted_email<br>duration<br> }

DS->>+DB: Find valid record matching code 

Note right of DS: ?<br>{<br>type: signin_code<br>code<br>}

DB-->>-DS: 

alt: if existing signin_code record

DS->>+DB: Update record as invalid 

Note right of DS: {<br>...<br>invalid: superseded<br>}

DB-->>-DS: 

end

Note over DS: Create  code<br>5 digits

Note over DS: Create expiry_time<br>based on duration

DS->>+DB: Create signin_code record

Note right of DS: { <br>type: signin_code<br>code<br>encrypted_email<br>expiry_time<br> }

DB-->>-DS: 

DS-XU: Send sms with code via GOV Notify 

DS-->>-R:   

R-->>U: Redirect /return/code

