sequenceDiagram

participant U as User

participant R as Runner

participant DS as User Datastore API

participant DB as User Datastore DB

U->>+R: POST /return/code/:code

Note right of U: code

Note over R: Get email, mobile<br>from current cookie

R-->>+DS: POST /service/:service/savereturn/signin/code/validate

Note right of R: {<br>code,<br>encrypted_email<br>}

DS->>+DB: Find matching record

Note right of DS: ?<br>{<br>code,<br>encrypted_email<br>}

DB-->>-DS: 

Note over DS: Check code <br>expiry date

DS-->>-R: {encrypted_details}

Note over R: Decrypt <br>encrypted_details

Note over R: Set cookie using id <br>and token from <br>encrypted_details

R-->>-U:  Redirect /return/authenticated
